// Large pool of personality quotes for doodle analysis
// Randomly select one quote per doodle for variety

export const PERSONALITY_QUOTES = [
  // Speed-based quotes (fast)
  "Whoa, you draw FAST! Your hand barely touches the screen",
  "Speed demon alert! This doodle happened in a flash",
  "Blink and you'd miss it - lightning-fast strokes here",
  "You're not drawing, you're RACING across the canvas",
  "Fast and furious! Your hand has places to be",
  "Quick sketcher vibes - no time to waste",
  "Zoom zoom! This doodle came out at warp speed",
  "Your hand moves faster than your thoughts can keep up",
  "Rapid fire creativity right here",
  "Speed drawing champion in the making",
  
  // Speed-based quotes (slow)
  "You take your sweet time with each stroke",
  "Slow and steady wins the doodle race",
  "Every line gets the VIP treatment here",
  "Patient artist alert! No rushing this masterpiece",
  "You're savoring every single moment of this doodle",
  "Careful and deliberate - that's your style",
  "Taking it slow, taking it smooth",
  "No rush, no stress, just pure focus",
  "Methodical magic happening here",
  "You believe good things take time",
  
  // Smoothness quotes (smooth)
  "Your lines flow like butter - so smooth!",
  "Silky smooth strokes all the way",
  "These curves are SATISFYING to look at",
  "Smooth operator! Your lines glide effortlessly",
  "Like ice skating on paper - pure grace",
  "Flowy, dreamy, perfectly smooth",
  "Your hand knows the way and it shows",
  "Smooth as silk, clean as a whistle",
  "These lines could put anyone in a trance",
  "Effortlessly elegant strokes",
  
  // Smoothness quotes (chaotic)
  "Zigzags, curves, chaos! Love the energy",
  "Your strokes go wherever they feel like",
  "Controlled chaos at its finest",
  "Wild lines with a mind of their own",
  "Unpredictable and that's what makes it cool",
  "Chaotic energy captured in every stroke",
  "Your doodle took the scenic route",
  "Messy? Nah, it's called CHARACTER",
  "Rules? What rules? Your lines are free",
  "Beautiful chaos in motion",
  
  // Color quotes (colorful)
  "Rainbow vibes! Every color made an appearance",
  "You're not afraid to throw ALL the colors at it",
  "Color explosion! And we're here for it",
  "Your palette is a party and everyone's invited",
  "More colors = more fun, right?",
  "Chromatic chaos in the best way possible",
  "You said yes to every color option",
  "Living life in full color mode",
  "Why pick one when you can have them all?",
  "Your doodle is a color festival",
  
  // Color quotes (minimal)
  "You stick to your favorites - classic move",
  "Less is more, and you nailed it",
  "Minimalist color palette for maximum impact",
  "You know what you like and you stick to it",
  "Simple colors, complex vibes",
  "Quality over quantity with these colors",
  "Your color choices are INTENTIONAL",
  "Focused palette, focused mind",
  "Sometimes one color is all you need",
  "Restraint is an art form too",
  
  // Pressure quotes (consistent)
  "Steady hand alert! Rock-solid pressure",
  "Your pressure stays consistent like clockwork",
  "Zen-level control over your strokes",
  "Steady as she goes - impressive control",
  "Your hand pressure is on autopilot perfection",
  "Consistent pressure = consistent vibes",
  "No shaky hands here, just pure stability",
  "You've got that steady hand magic",
  "Pressure control: MASTERED",
  "Calm, cool, and collected strokes",
  
  // Pressure quotes (varied)
  "Your pressure tells a story - soft then HARD",
  "Emotional strokes! We can feel the intensity",
  "You press hard when it matters",
  "Dynamic pressure = dynamic personality",
  "Your doodle has FEELINGS and we're here for it",
  "Pressure changes like a heartbeat",
  "Soft whispers and loud shouts in one doodle",
  "Your hand expresses what words can't",
  "Pressure variance is your secret weapon",
  "Every stroke has its own intensity",
  
  // Brush variety quotes
  "Brush collector spotted! You tried everything",
  "Tool hoarder energy - love to see it",
  "Why use one brush when you can use TEN?",
  "You're exploring every tool in the box",
  "Brush experimenter extraordinaire",
  "Variety is the spice of doodling",
  "You're not picky - you love ALL the brushes",
  "Tool switcher pro right here",
  "Every brush deserves a chance",
  "Brush variety = creative variety",
  
  // Direction changes quotes (many)
  "Your hand never stops turning - what a journey!",
  "This doodle went on an ADVENTURE",
  "Twists, turns, and everything in between",
  "Your lines took the scenic route",
  "Direction changes? More like direction PARTY",
  "Your doodle has more turns than a rollercoaster",
  "Winding paths and wild curves everywhere",
  "Your hand choreographed a whole dance",
  "Complex paths for a complex mind",
  "Every angle got its moment to shine",
  
  // Direction changes quotes (few)
  "Straight shooter! Your lines know where they're going",
  "Direct and to the point - no detours here",
  "Your lines don't mess around",
  "Straight paths, clear intentions",
  "No zigzags, just pure direction",
  "Your strokes are on a mission",
  "Efficiency is your middle name",
  "Clean lines, clear mind",
  "Straight forward and proud of it",
  "Your doodle knows its destination",
  
  // General creative quotes
  "This doodle screams PERSONALITY",
  "Your style is unmistakably YOU",
  "Creative energy is off the charts here",
  "You're not following rules, you're making them",
  "This is what creative freedom looks like",
  "Your doodle has main character energy",
  "Artistic chaos in the best way",
  "You drew this with your whole heart",
  "This doodle is unapologetically yours",
  "Creative expression at its finest",
  
  // Playful quotes
  "Did you have fun? Because it SHOWS",
  "This doodle is pure joy captured",
  "You were vibing and we can tell",
  "Playful energy radiates from every stroke",
  "This looks like it was FUN to make",
  "Your inner child was definitely driving",
  "No stress, just vibes",
  "This doodle is a mood and a half",
  "You were in the ZONE",
  "Pure unfiltered creativity",
  
  // Detailed quotes
  "Wow, you didn't skip a single pixel",
  "Detail level: MAXIMUM",
  "You really went for it with this one",
  "Layers upon layers of goodness",
  "This doodle has DEPTH",
  "You put your whole soul into this",
  "Dedication level: OFF THE CHARTS",
  "Every corner got attention",
  "This is what commitment looks like",
  "You really said 'go big or go home'",
  
  // Simple quotes
  "Sometimes simple is the most powerful",
  "Less is more and you proved it",
  "Clean, simple, perfect",
  "You know the power of restraint",
  "Simplicity is your superpower",
  "No fluff, just the good stuff",
  "Minimalist magic right here",
  "You said what you needed to say",
  "Simple doesn't mean boring",
  "Elegance in simplicity",
  
  // Experimental quotes
  "You're not afraid to try new things",
  "Experimental vibes all over this",
  "This doodle is a playground",
  "You're pushing boundaries and we love it",
  "Creative risks = creative rewards",
  "You're exploring uncharted territory",
  "This is what innovation looks like",
  "You're writing your own rules",
  "Fearless creativity on display",
  "You're a doodle pioneer",
  
  // Confident quotes
  "Confident strokes from start to finish",
  "You know what you're doing",
  "No hesitation, just pure confidence",
  "Your hand moves with authority",
  "This doodle radiates self-assurance",
  "You drew this like a boss",
  "Confidence is your secret ingredient",
  "You own every stroke",
  "This is what certainty looks like",
  "Your confidence is contagious",
  
  // Unique style quotes
  "Nobody else doodles quite like you",
  "Your style is one of a kind",
  "This has YOUR signature all over it",
  "Uniquely you from start to finish",
  "Your artistic fingerprint is everywhere",
  "This could only come from you",
  "Original content right here",
  "You're not copying anyone",
  "Your style is your superpower",
  "This is authentically YOU",
  
  // Energy quotes
  "The energy in this doodle is ELECTRIC",
  "You brought the ENERGY",
  "This doodle is ALIVE",
  "Vibrant energy captured in pixels",
  "You channeled some serious power here",
  "This doodle has a pulse",
  "Energy levels: MAXIMUM",
  "You were FEELING it",
  "This doodle could power a city",
  "Pure creative electricity",
  
  // Chill quotes
  "Chill vibes only in this doodle",
  "You were in your zen zone",
  "Relaxed and it shows",
  "This doodle is a whole mood",
  "Calm energy radiates from this",
  "You were at peace while making this",
  "Tranquil vibes captured perfectly",
  "This doodle is a meditation",
  "Peaceful creativity at work",
  "You found your flow state",
  
  // Bold quotes
  "BOLD choices all around!",
  "You went HARD on this one",
  "No holding back here",
  "Fearless and it shows",
  "You made a STATEMENT",
  "This doodle demands attention",
  "Bold moves, bold results",
  "You didn't come to play",
  "This is what courage looks like",
  "You went all in",
  
  // Spontaneous quotes
  "Pure spontaneity captured",
  "You let your hand do the thinking",
  "Unplanned and unfiltered",
  "This doodle just HAPPENED",
  "No script, just vibes",
  "Spontaneous creativity is the best kind",
  "You followed your instincts",
  "This is what freedom looks like",
  "Unscripted and authentic",
  "You let it flow naturally",
  
  // Thoughtful quotes
  "Every stroke was a choice",
  "You thought this through",
  "Intentional from start to finish",
  "This doodle has PURPOSE",
  "You knew exactly what you wanted",
  "Thoughtful creativity on display",
  "Every detail was considered",
  "You drew with intention",
  "This is mindful art",
  "Purposeful and powerful",
  
  // Fun random quotes
  "This doodle sparks joy!",
  "Your creativity is showing",
  "This is what happens when you let loose",
  "You're a natural at this",
  "This doodle has personality for DAYS",
  "You made something special here",
  "This is frame-worthy honestly",
  "Your talent is showing",
  "This doodle is a whole vibe",
  "You should be proud of this",
  "This is giving main character energy",
  "Your artistic voice is LOUD",
  "This doodle tells a story",
  "You captured a moment perfectly",
  "This is what passion looks like",
  "Your creativity knows no bounds",
  "This doodle is a masterpiece in progress",
  "You're leveling up with each stroke",
  "This is your canvas, your rules",
  "You're creating your own language",
];

// Function to get a random quote
export function getRandomQuote(): string {
  const randomIndex = Math.floor(Math.random() * PERSONALITY_QUOTES.length);
  return PERSONALITY_QUOTES[randomIndex];
}
